apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: 5432
{{- if .Values.db.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{- end }}
