apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-result
  labels:
    app: result
spec:
  type: {{ .Values.result.service.type }}
  selector:
    app: result
  ports:
    - port: {{ .Values.result.service.port }}
      targetPort: 80
