apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote
  labels:
    app: vote
spec:
  type: {{ .Values.vote.service.type }}
  selector:
    app: vote
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: 80
